"""Client Format Compatibility Test Suite.

This suite exercises the output files generated by the actions (the static index
and signatures) against a real local Flatpak client, confirming that:
1. Flatpak client can parse the generated index/static repository index.
2. Flatpak client successfully downloads, verify-signatures, and installs
   applications from the mock repository served over HTTP.

Note: Action-level integration tests (running composite actions end-to-end)
are performed via the GitHub Actions runner in `.github/workflows/test.yml`.
"""

import base64
import http.server
import json
import os
import pathlib
import shutil
import socket
import subprocess
import tempfile
import threading
import time
import urllib.request
from collections.abc import Generator

import pytest

# Skip all tests in this module if required command line tools are missing
_REQUIRED_BINARIES = ["ostree", "flatpak", "skopeo"]
_MISSING_BINARIES = [b for b in _REQUIRED_BINARIES if not shutil.which(b)]
_HAS_CONTAINER = bool(shutil.which("podman") or shutil.which("docker"))

if _MISSING_BINARIES or not _HAS_CONTAINER:
    _reasons = []
    if _MISSING_BINARIES:
        _reasons.append(f"missing command(s): {', '.join(_MISSING_BINARIES)}")
    if not _HAS_CONTAINER:
        _reasons.append("no container manager (podman/docker) found")
    pytestmark = pytest.mark.skip(reason=f"Missing E2E environment: {'; '.join(_reasons)}")

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
TMP_ROOT = REPO_ROOT / "tests" / "tmp_integration"


def find_free_port() -> int:
    """Find a free port on localhost."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def run_command_with_log(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    """Run a subprocess command, capturing and printing stdout/stderr on failure."""
    try:
        return subprocess.run(cmd, check=True, capture_output=True, text=True, **kwargs)
    except subprocess.CalledProcessError as e:
        print(f"Command failed: {' '.join(cmd)}")
        print(f"Stdout:\n{e.stdout}")
        print(f"Stderr:\n{e.stderr}")
        raise


def set_remote_signature_lookaside(
    flatpak_user_dir: pathlib.Path, remote_name: str, url: str
) -> None:
    """Manually set signature lookaside in flatpak repo config to support older flatpak versions."""
    import configparser

    config_path = flatpak_user_dir / "repo" / "config"
    if not config_path.exists():
        raise FileNotFoundError(f"Flatpak repo config not found at {config_path}")

    config = configparser.RawConfigParser()
    config.read(config_path)
    section = f'remote "{remote_name}"'
    if not config.has_section(section):
        config.add_section(section)
    config.set(section, "xa.signature-lookaside", url)
    with open(config_path, "w") as f:
        config.write(f)


def get_container_manager() -> str:
    """Find available container manager: podman or docker."""
    if shutil.which("podman"):
        return "podman"
    if shutil.which("docker"):
        return "docker"
    raise RuntimeError("Neither podman nor docker is installed")


@pytest.fixture(scope="module")
def container_manager() -> str:
    return get_container_manager()


@pytest.fixture
def registry_server(container_manager: str) -> Generator[int, None, None]:
    """Start an ephemeral registry:2 container and yield its port."""
    port = find_free_port()
    # Use a port-unique name to make the suite safe under pytest -n parallelism
    name = f"aep-test-registry-{port}"

    # Force stop any existing test registry
    subprocess.run([container_manager, "rm", "-f", name], capture_output=True)

    # Start registry
    cmd = [
        container_manager,
        "run",
        "-d",
        "-p",
        f"127.0.0.1:{port}:5000",
        "--name",
        name,
        "-e",
        "REGISTRY_STORAGE_DELETE_ENABLED=true",
        "registry:2",
    ]
    subprocess.run(cmd, check=True, capture_output=True)

    # Wait for registry to start
    started = False
    for _ in range(30):
        try:
            with urllib.request.urlopen(f"http://127.0.0.1:{port}/v2/") as response:
                if response.status == 200:
                    started = True
                    break
        except Exception:
            time.sleep(0.5)

    if not started:
        subprocess.run([container_manager, "rm", "-f", name], capture_output=True)
        raise RuntimeError(f"Local OCI registry failed to start on port {port}")

    yield port

    # Cleanup
    subprocess.run([container_manager, "rm", "-f", name], check=True, capture_output=True)


@pytest.fixture
def test_dir() -> Generator[pathlib.Path, None, None]:
    """Provide a clean workspace directory."""
    if TMP_ROOT.exists():
        shutil.rmtree(TMP_ROOT)
    TMP_ROOT.mkdir(parents=True, exist_ok=True)
    yield TMP_ROOT
    if TMP_ROOT.exists():
        try:
            shutil.rmtree(TMP_ROOT)
        except PermissionError:
            # Sometime flatpak leaves locks or mounts, ignore on cleanup
            pass


@pytest.fixture
def flatpak_user_dir(test_dir: pathlib.Path, monkeypatch: pytest.MonkeyPatch) -> pathlib.Path:
    """Set up an isolated FLATPAK_USER_DIR for client sandboxing."""
    sandbox = test_dir / "flatpak_user"
    sandbox.mkdir(parents=True)
    # flatpak has no system-dir override; --user keeps all state in FLATPAK_USER_DIR.
    monkeypatch.setenv("FLATPAK_USER_DIR", str(sandbox))
    return sandbox


class EphemeralHTTPServer(http.server.ThreadingHTTPServer):
    allow_reuse_address = True


@pytest.fixture
def web_server(test_dir: pathlib.Path) -> Generator[int, None, None]:
    """Start an HTTP server to serve the generated site directory."""
    port = find_free_port()
    site_dir = test_dir / "site"
    site_dir.mkdir(parents=True, exist_ok=True)

    def handler(*args, **kwargs):
        return http.server.SimpleHTTPRequestHandler(*args, directory=str(site_dir), **kwargs)

    server = EphemeralHTTPServer(("127.0.0.1", port), handler)

    thread = threading.Thread(target=server.serve_forever)
    thread.daemon = True
    thread.start()

    # Wait for web server to start
    for _ in range(20):
        try:
            with urllib.request.urlopen(f"http://127.0.0.1:{port}/"):
                break
        except Exception:
            time.sleep(0.1)

    yield port

    server.shutdown()
    thread.join()


@pytest.fixture
def gpg_key(test_dir: pathlib.Path) -> tuple[str, str]:
    """Generate an ephemeral GPG key pair and return (fingerprint, armored_private_key)."""
    gnupghome = test_dir / "gpg"
    gnupghome.mkdir(parents=True, exist_ok=True)
    gnupghome.chmod(0o700)

    params_file = gnupghome / "params"
    params_file.write_text(
        "%no-protection\n"
        "Key-Type: RSA\n"
        "Key-Length: 2048\n"
        "Name-Real: AetherPak E2E\n"
        "Name-Email: e2e@aetherpak.local\n"
        "Expire-Date: 0\n"
        "%commit\n"
    )

    env = {**os.environ, "GNUPGHOME": str(gnupghome)}
    subprocess.run(
        ["gpg", "--batch", "--gen-key", str(params_file)], env=env, check=True, capture_output=True
    )

    # Resolve fingerprint
    res = subprocess.run(
        ["gpg", "--list-secret-keys", "--with-colons"],
        env=env,
        check=True,
        capture_output=True,
        text=True,
    )
    fpr = ""
    for line in res.stdout.splitlines():
        if line.startswith("fpr:"):
            fpr = line.split(":")[9]
            break

    assert fpr, "Could not find generated GPG key fingerprint"

    # Export private key
    priv_res = subprocess.run(
        ["gpg", "--armor", "--export-secret-keys", fpr],
        env=env,
        check=True,
        capture_output=True,
        text=True,
    )

    return fpr, priv_res.stdout


def create_mock_app_repo(repo_path: pathlib.Path, app_id: str, version: str = "1.0") -> None:
    """Build a minimal valid Flatpak OSTree repository containing a mock app structure."""
    if repo_path.exists():
        shutil.rmtree(repo_path)
    subprocess.run(["ostree", "init", "--mode=archive", f"--repo={repo_path}"], check=True)

    with tempfile.TemporaryDirectory() as tmpdir_app, tempfile.TemporaryDirectory() as tmpdir_repo:
        app_dir = pathlib.Path(tmpdir_app)
        tmp_repo = pathlib.Path(tmpdir_repo) / "repo"

        files_dir = app_dir / "files"
        files_dir.mkdir(parents=True)
        (files_dir / "hello").write_text(f"echo 'Hello version {version}'\n")
        (files_dir / "hello").chmod(0o755)

        metadata = (
            "[Application]\n"
            f"name={app_id}\n"
            "runtime=org.freedesktop.Platform/x86_64/23.08\n"
            "sdk=org.freedesktop.Sdk/x86_64/23.08\n"
            "command=hello\n"
        )
        (app_dir / "metadata").write_text(metadata)

        # We need to write the commit to a temporary repo first, then use
        # flatpak build-commit-from to commit it to the target repo with correct ref-binding.
        subprocess.run(["ostree", "init", "--mode=archive", f"--repo={tmp_repo}"], check=True)

        subprocess.run(
            [
                "ostree",
                "commit",
                f"--repo={tmp_repo}",
                "--branch=temp-branch",
                "--owner-uid=0",
                "--owner-gid=0",
                "--canonical-permissions",
                f"--add-metadata-string=xa.metadata={metadata}",
                "-s",
                "Mock application commit",
                str(app_dir),
            ],
            check=True,
            capture_output=True,
        )

        subprocess.run(
            [
                "flatpak",
                "build-commit-from",
                f"--src-repo={tmp_repo}",
                "--src-ref=temp-branch",
                "--no-update-summary",
                str(repo_path),
                f"app/{app_id}/x86_64/stable",
            ],
            check=True,
            capture_output=True,
        )


def push_to_registry(
    repo_path: pathlib.Path, app_id: str, registry_port: int, image_name: str, tag: str
) -> str:
    """Convert OSTree to OCI bundle and push to the local OCI registry."""
    with tempfile.TemporaryDirectory() as tmpdir:
        oci_dir = pathlib.Path(tmpdir) / "oci"
        subprocess.run(
            [
                "flatpak",
                "build-bundle",
                "--oci",
                "--arch=x86_64",
                str(repo_path),
                str(oci_dir),
                app_id,
                "stable",
            ],
            check=True,
            capture_output=True,
        )

        subprocess.run(
            [
                "skopeo",
                "copy",
                "--dest-tls-verify=false",
                "--all",
                f"oci:{oci_dir}",
                f"docker://localhost:{registry_port}/{image_name}:{tag}",
            ],
            check=True,
            capture_output=True,
        )

        # Query digest
        res = subprocess.run(
            [
                "skopeo",
                "inspect",
                "--tls-verify=false",
                f"docker://localhost:{registry_port}/{image_name}:{tag}",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        return json.loads(res.stdout)["Digest"]


def run_indexing(
    site_dir: pathlib.Path,
    registry_port: int,
    image_name: str,
    digest: str,
    app_id: str,
    tag: str,
    insecure: bool = True,
) -> None:
    """Execute merge_index.py to insert the OCI coordinates into index/static."""
    index_path = site_dir / "index" / "static"
    # Match the production insecure-registry scheme mapping: http when insecure, else https
    scheme = "http" if insecure else "https"
    registry_url = f"{scheme}://localhost:{registry_port}"

    # Resolve the correct OCI tag to query the registry with
    if "-" in tag:
        oci_tag = tag
    else:
        oci_tag = f"{app_id.replace('.', '_')}-{tag}-x86_64"

    # We resolve labels from the local skopeo inspect
    res = subprocess.run(
        [
            "skopeo",
            "inspect",
            "--tls-verify=false",
            f"docker://localhost:{registry_port}/{image_name}:{oci_tag}",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    labels = json.loads(res.stdout).get("Labels", {})
    labels_file = site_dir / "labels.json"
    labels_file.write_text(json.dumps(labels))

    subprocess.run(
        [
            "python3",
            str(REPO_ROOT / "publish" / "merge_index.py"),
            "--index-path",
            str(index_path),
            "--registry",
            registry_url,
            "--name",
            image_name,
            "--digest",
            digest,
            "--ref",
            f"app/{app_id}/x86_64/stable",
            "--labels-file",
            str(labels_file),
            "--tag",
            oci_tag,
            "--arch",
            "x86_64",
        ],
        check=True,
    )


@pytest.mark.integration
def test_scenario1_manifest_flow(
    test_dir: pathlib.Path, registry_server: int, web_server: int, flatpak_user_dir: pathlib.Path
) -> None:
    """Scenario 1: Single-App Manifest-Based Build & Install."""
    app_id = "org.flatpak.MockApp"
    repo_path = test_dir / "repo"
    site_dir = test_dir / "site"
    image_name = "aetherpak/mock-app"
    tag = "org_flatpak_MockApp-stable-x86_64"

    # 1. Build app
    create_mock_app_repo(repo_path, app_id)

    # 2. Push to local registry
    digest = push_to_registry(repo_path, app_id, registry_server, image_name, tag)

    # 3. Index and generate index/static
    run_indexing(site_dir, registry_server, image_name, digest, app_id, tag)

    # 4. Generate .flatpakrepo and ref files
    remote_name = "mock-remote"
    subprocess.run(
        [
            "python3",
            str(REPO_ROOT / "publish" / "gen_flatpakrefs.py"),
            "--index-path",
            str(site_dir / "index" / "static"),
            "--out-dir",
            str(site_dir / "refs"),
            "--url",
            f"oci+http://localhost:{web_server}",
            "--remote-name",
            remote_name,
            "--runtime-repo",
            "https://dl.flathub.org/repo/flathub.flatpakrepo",
        ],
        check=True,
    )

    # 5. Client install and verification
    subprocess.run(
        [
            "flatpak",
            "remote-add",
            "--user",
            "--no-gpg-verify",
            remote_name,
            f"oci+http://localhost:{web_server}",
        ],
        check=True,
    )

    # Verify app shows in remote-ls
    ls_res = subprocess.run(
        ["flatpak", "remote-ls", "--user", remote_name], check=True, capture_output=True, text=True
    )
    assert app_id in ls_res.stdout

    # Install --no-deps to skip pulling external runtime from Flathub
    subprocess.run(
        ["flatpak", "install", "--user", "-y", "--no-deps", remote_name, app_id], check=True
    )

    # Verify installation
    info_res = subprocess.run(
        ["flatpak", "info", "--user", app_id], check=True, capture_output=True, text=True
    )
    assert app_id in info_res.stdout

    # Uninstall & remote-delete
    subprocess.run(["flatpak", "uninstall", "--user", "-y", app_id], check=True)
    subprocess.run(["flatpak", "remote-delete", "--user", remote_name], check=True)


@pytest.mark.integration
def test_scenario2_bundle_import(
    test_dir: pathlib.Path, registry_server: int, web_server: int, flatpak_user_dir: pathlib.Path
) -> None:
    """Scenario 2: Single-App Bundle Import & Install."""
    app_id = "org.flatpak.BundleApp"
    repo_path = test_dir / "repo"
    bundle_path = test_dir / "app.flatpak"
    site_dir = test_dir / "site"
    image_name = "aetherpak/bundle-app"
    tag = "org_flatpak_BundleApp-stable-x86_64"

    # 1. Build app and export to bundle
    create_mock_app_repo(repo_path, app_id)
    subprocess.run(
        ["flatpak", "build-bundle", str(repo_path), str(bundle_path), app_id, "stable"],
        check=True,
        capture_output=True,
    )

    # Delete source repo to verify E2E bundle-only import
    shutil.rmtree(repo_path)

    # 2. Import bundle to new repo
    imported_repo = test_dir / "imported_repo"
    subprocess.run(["ostree", "init", "--mode=archive", f"--repo={imported_repo}"], check=True)
    subprocess.run(
        ["flatpak", "build-import-bundle", str(imported_repo), str(bundle_path)],
        check=True,
        capture_output=True,
    )

    # 3. Push and index
    digest = push_to_registry(imported_repo, app_id, registry_server, image_name, tag)
    run_indexing(site_dir, registry_server, image_name, digest, app_id, tag)

    # 4. Generate refs
    remote_name = "bundle-remote"
    subprocess.run(
        [
            "python3",
            str(REPO_ROOT / "publish" / "gen_flatpakrefs.py"),
            "--index-path",
            str(site_dir / "index" / "static"),
            "--out-dir",
            str(site_dir / "refs"),
            "--url",
            f"oci+http://localhost:{web_server}",
            "--remote-name",
            remote_name,
            "--runtime-repo",
            "https://dl.flathub.org/repo/flathub.flatpakrepo",
        ],
        check=True,
    )

    # 5. Verify install
    subprocess.run(
        [
            "flatpak",
            "remote-add",
            "--user",
            "--no-gpg-verify",
            remote_name,
            f"oci+http://localhost:{web_server}",
        ],
        check=True,
    )
    subprocess.run(
        ["flatpak", "install", "--user", "-y", "--no-deps", remote_name, app_id], check=True
    )
    info_res = subprocess.run(
        ["flatpak", "info", "--user", app_id], check=True, capture_output=True, text=True
    )
    assert app_id in info_res.stdout

    subprocess.run(["flatpak", "uninstall", "--user", "-y", app_id], check=True)
    subprocess.run(["flatpak", "remote-delete", "--user", remote_name], check=True)


@pytest.mark.integration
def test_scenario3_gpg_signing_enforcement(
    test_dir: pathlib.Path,
    registry_server: int,
    web_server: int,
    flatpak_user_dir: pathlib.Path,
    gpg_key: tuple[str, str],
) -> None:
    """Scenario 3: GPG-Signed Deployment Flow & Signature Enforcement."""
    fpr, priv_key = gpg_key
    app_id = "org.flatpak.SignedApp"
    repo_path = test_dir / "repo"
    site_dir = test_dir / "site"
    image_name = "aetherpak/signed-app"
    tag = "org_flatpak_SignedApp-stable-x86_64"

    create_mock_app_repo(repo_path, app_id)

    # Sign during skopeo push
    # We stage registries.d YAML mapping local host to our site's sigs dir
    sigs_dir = site_dir / "sigs"
    sigs_dir.mkdir(parents=True, exist_ok=True)

    # Write registries.d
    regd_dir = test_dir / "registries.d"
    regd_dir.mkdir(exist_ok=True)
    (regd_dir / "aetherpak.yaml").write_text(
        f"docker:\n  localhost:{registry_server}:\n    lookaside-staging: file://{sigs_dir.resolve()}\n"
    )

    # Import private key to a temp GNUPGHOME for the push step
    gnupghome = test_dir / "gpg_temp"
    gnupghome.mkdir(exist_ok=True)
    gnupghome.chmod(0o700)
    env = {**os.environ, "GNUPGHOME": str(gnupghome)}
    subprocess.run(
        ["gpg", "--batch", "--import"],
        input=priv_key,
        env=env,
        check=True,
        capture_output=True,
        text=True,
    )

    # Convert and push with signing
    with tempfile.TemporaryDirectory() as tmpdir:
        oci_dir = pathlib.Path(tmpdir) / "oci"
        subprocess.run(
            [
                "flatpak",
                "build-bundle",
                "--oci",
                "--arch=x86_64",
                str(repo_path),
                str(oci_dir),
                app_id,
                "stable",
            ],
            check=True,
            capture_output=True,
        )

        subprocess.run(
            [
                "skopeo",
                f"--registries.d={regd_dir}",
                "copy",
                "--dest-tls-verify=false",
                f"--sign-by={fpr}",
                "--all",
                f"oci:{oci_dir}",
                f"docker://localhost:{registry_server}/{image_name}:{tag}",
            ],
            env=env,
            check=True,
            capture_output=True,
        )

    res = subprocess.run(
        [
            "skopeo",
            "inspect",
            "--tls-verify=false",
            f"docker://localhost:{registry_server}/{image_name}:{tag}",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    digest = json.loads(res.stdout)["Digest"]

    # Export public key (ASCII armored for flatpak client import)
    pub_res = subprocess.run(
        ["gpg", "--armor", "--export", fpr], env=env, check=True, capture_output=True, text=True
    )
    (sigs_dir / "key.asc").write_text(pub_res.stdout)

    # Export binary public key and base64-encode it for gen_flatpakrefs.py
    pub_bin_res = subprocess.run(["gpg", "--export", fpr], env=env, check=True, capture_output=True)
    gpg_key_b64 = base64.b64encode(pub_bin_res.stdout).decode("utf-8")
    (sigs_dir / "key.b64").write_text(gpg_key_b64)

    # Write signing.json manifest
    subprocess.run(
        [
            "python3",
            str(REPO_ROOT / "publish" / "signing.py"),
            "manifest",
            "--out",
            str(sigs_dir / "signing.json"),
            "--sig-dir",
            "sigs",
            "--fingerprint",
            fpr,
            "--remote-name",
            "mock-signed-remote",
        ],
        check=True,
    )

    run_indexing(site_dir, registry_server, image_name, digest, app_id, tag)

    # Generate ref file with embedded GPG key + lookaside
    subprocess.run(
        [
            "python3",
            str(REPO_ROOT / "publish" / "gen_flatpakrefs.py"),
            "--index-path",
            str(site_dir / "index" / "static"),
            "--out-dir",
            str(site_dir / "refs"),
            "--url",
            f"oci+http://localhost:{web_server}",
            "--remote-name",
            "mock-signed-remote",
            "--runtime-repo",
            "https://dl.flathub.org/repo/flathub.flatpakrepo",
            "--gpg-key-base64-file",
            str(sigs_dir / "key.b64"),
            "--signature-lookaside",
            f"http://localhost:{web_server}/sigs",
        ],
        check=True,
    )

    # Verify verified install (GPG verification enabled)
    remote_name = "mock-signed-remote"
    run_command_with_log(
        [
            "flatpak",
            "remote-add",
            "--user",
            f"--gpg-import={sigs_dir / 'key.asc'}",
            remote_name,
            f"oci+http://localhost:{web_server}",
        ]
    )
    set_remote_signature_lookaside(
        flatpak_user_dir, remote_name, f"http://localhost:{web_server}/sigs"
    )

    # Install should pass verification
    subprocess.run(
        ["flatpak", "install", "--user", "-y", "--no-deps", remote_name, app_id], check=True
    )
    info_res = subprocess.run(
        ["flatpak", "info", "--user", app_id], check=True, capture_output=True, text=True
    )
    assert app_id in info_res.stdout

    # Clean client sandbox to verify enforcement on fresh install
    subprocess.run(["flatpak", "uninstall", "--user", "-y", app_id], check=True)
    subprocess.run(["flatpak", "remote-delete", "--user", remote_name], check=True)
    shutil.rmtree(flatpak_user_dir)
    flatpak_user_dir.mkdir()

    # TAMPER with the signature file
    sig_rel = f"sigs/{image_name}@{digest.replace(':', '=')}/signature-1"
    sig_file = site_dir / sig_rel
    assert sig_file.is_file(), f"Signature file does not exist at {sig_file}"
    sig_file.write_text("TAMPERED_SIGNATURE_BYTES")

    # Re-add remote with key and lookaside
    run_command_with_log(
        [
            "flatpak",
            "remote-add",
            "--user",
            f"--gpg-import={sigs_dir / 'key.asc'}",
            remote_name,
            f"oci+http://localhost:{web_server}",
        ]
    )
    set_remote_signature_lookaside(
        flatpak_user_dir, remote_name, f"http://localhost:{web_server}/sigs"
    )

    # Install MUST fail now due to tampered signature
    res_tamper = subprocess.run(
        ["flatpak", "install", "--user", "-y", "--no-deps", remote_name, app_id],
        capture_output=True,
        text=True,
    )

    assert res_tamper.returncode != 0
    assert (
        "signature" in res_tamper.stderr.lower()
        or "verify" in res_tamper.stderr.lower()
        or "valid" in res_tamper.stderr.lower()
    )


@pytest.mark.integration
def test_scenario4_multi_app(
    test_dir: pathlib.Path, registry_server: int, web_server: int, flatpak_user_dir: pathlib.Path
) -> None:
    """Scenario 4: Multi-App Matrix Build, Aggregate & Install."""
    app_a = "org.flatpak.AppA"
    app_b = "org.flatpak.AppB"
    site_dir = test_dir / "site"

    # 1. Build and push both applications
    repo_a = test_dir / "repo_a"
    create_mock_app_repo(repo_a, app_a, version="2.0")
    digest_a = push_to_registry(
        repo_a, app_a, registry_server, "aetherpak/app-a", "org_flatpak_AppA-stable-x86_64"
    )

    repo_b = test_dir / "repo_b"
    create_mock_app_repo(repo_b, app_b, version="3.0")
    digest_b = push_to_registry(
        repo_b, app_b, registry_server, "aetherpak/app-b", "org_flatpak_AppB-stable-x86_64"
    )

    # 2. Run merging index for both apps (aggregate them)
    run_indexing(site_dir, registry_server, "aetherpak/app-a", digest_a, app_a, "stable")
    run_indexing(site_dir, registry_server, "aetherpak/app-b", digest_b, app_b, "stable")

    # 3. Generate refs
    remote_name = "multi-remote"
    subprocess.run(
        [
            "python3",
            str(REPO_ROOT / "publish" / "gen_flatpakrefs.py"),
            "--index-path",
            str(site_dir / "index" / "static"),
            "--out-dir",
            str(site_dir / "refs"),
            "--url",
            f"oci+http://localhost:{web_server}",
            "--remote-name",
            remote_name,
            "--runtime-repo",
            "https://dl.flathub.org/repo/flathub.flatpakrepo",
        ],
        check=True,
    )

    # 4. Install and verify both
    subprocess.run(
        [
            "flatpak",
            "remote-add",
            "--user",
            "--no-gpg-verify",
            remote_name,
            f"oci+http://localhost:{web_server}",
        ],
        check=True,
    )
    subprocess.run(
        ["flatpak", "install", "--user", "-y", "--no-deps", remote_name, app_a], check=True
    )
    subprocess.run(
        ["flatpak", "install", "--user", "-y", "--no-deps", remote_name, app_b], check=True
    )

    info_a = subprocess.run(
        ["flatpak", "info", "--user", app_a], check=True, capture_output=True, text=True
    )
    info_b = subprocess.run(
        ["flatpak", "info", "--user", app_b], check=True, capture_output=True, text=True
    )
    assert app_a in info_a.stdout
    assert app_b in info_b.stdout


@pytest.mark.integration
def test_scenario5_delisting_reconcile(
    test_dir: pathlib.Path,
    registry_server: int,
    web_server: int,
    flatpak_user_dir: pathlib.Path,
    container_manager: str,
) -> None:
    """Scenario 5: Reconciliation & Delisting verification."""
    app_a = "org.flatpak.AppA"
    app_b = "org.flatpak.AppB"
    site_dir = test_dir / "site"

    # 1. Deploy both app-a and app-b
    repo_a = test_dir / "repo_a"
    create_mock_app_repo(repo_a, app_a)
    digest_a = push_to_registry(
        repo_a, app_a, registry_server, "aetherpak/app-a", "org_flatpak_AppA-stable-x86_64"
    )

    repo_b = test_dir / "repo_b"
    create_mock_app_repo(repo_b, app_b)
    digest_b = push_to_registry(
        repo_b, app_b, registry_server, "aetherpak/app-b", "org_flatpak_AppB-stable-x86_64"
    )

    run_indexing(site_dir, registry_server, "aetherpak/app-a", digest_a, app_a, "stable")
    run_indexing(site_dir, registry_server, "aetherpak/app-b", digest_b, app_b, "stable")

    # Confirm both are initially serving
    remote_name = "reconcile-remote"
    subprocess.run(
        [
            "flatpak",
            "remote-add",
            "--user",
            "--no-gpg-verify",
            remote_name,
            f"oci+http://localhost:{web_server}",
        ],
        check=True,
    )
    ls_res = subprocess.run(
        ["flatpak", "remote-ls", "--user", remote_name], check=True, capture_output=True, text=True
    )
    assert app_a in ls_res.stdout
    assert app_b in ls_res.stdout

    # 2. Simulate de-listing app-b by deleting it from the registry
    subprocess.run(
        [
            "skopeo",
            "delete",
            "--tls-verify=false",
            f"docker://localhost:{registry_server}/aetherpak/app-b:org_flatpak_AppB-stable-x86_64",
        ],
        check=True,
    )

    # 3. Run reconcile.py. It will check "aetherpak/app-b" presence, fail to locate it, and drop it.
    subprocess.run(
        [
            "python3",
            str(REPO_ROOT / "publish" / "reconcile.py"),
            "--index-path",
            str(site_dir / "index" / "static"),
            "--registry",
            f"http://localhost:{registry_server}",
            "--insecure",
        ],
        check=True,
    )

    # 4. Verify index static content
    index_data = json.loads((site_dir / "index" / "static").read_text())
    active_names = [r["Name"] for r in index_data["Results"]]
    assert "aetherpak/app-a" in active_names
    assert "aetherpak/app-b" not in active_names

    # 5. Flush client-side cache and verify
    subprocess.run(["flatpak", "remote-delete", "--user", remote_name], check=True)
    subprocess.run(
        [
            "flatpak",
            "remote-add",
            "--user",
            "--no-gpg-verify",
            remote_name,
            f"oci+http://localhost:{web_server}",
        ],
        check=True,
    )

    ls_reconciled = subprocess.run(
        ["flatpak", "remote-ls", "--user", remote_name], check=True, capture_output=True, text=True
    )
    assert app_a in ls_reconciled.stdout
    assert app_b not in ls_reconciled.stdout

    # Install app-a passes, app-b fails
    subprocess.run(
        ["flatpak", "install", "--user", "-y", "--no-deps", remote_name, app_a], check=True
    )
    res_b = subprocess.run(
        ["flatpak", "install", "--user", "-y", "--no-deps", remote_name, app_b],
        capture_output=True,
        text=True,
    )
    assert res_b.returncode != 0
